---
services:
  ci:
    build:
      context: .
    working_dir: /app
    environment:
      - CI
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_SENDER
  app:
    extends:
      service: ci
    volumes:
      - ./:/app:rw
      - /app/.venv  # exclude .venv from the volume mount
