---
name: release

on:
  release:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/{{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/bake-action@v6
        with:
          load: true
          set: |
            *.cache-to=type=gha,mode=max                                                                                
            *.cache-from=type=gha
      - run: scripts/build.sh
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
